---
- name: Check if backup phase started
  k8s_facts:
    kind: MigMigration
    api_version: v1alpha1
    namespace: mig
    name: "{{ migration_name }}" 
  register: backup
  until: backup.resources[0].status.phase == "BackupStarted"
  retries: 60
  delay: 5

- name: Check if restore phase started
  k8s_facts:
    kind: MigMigration
    api_version: v1alpha1
    namespace: mig
    name: "{{ migration_name }}"
  register: restore
  until: restore.resources[0].status.phase == "RestoreStarted"
  retries: 60
  delay: 5

- name: Check if migration completed
  k8s_facts:
    kind: MigMigration
    api_version: v1alpha1
    namespace: mig
    name: "{{ migration_name }}"
  register: migration
  until: migration.resources[0].status.phase == "Completed"
  retries: 60
  delay: 5
