- name: Include required vars
  include_vars:
    file: "{{ playbook_dir }}/config/mig_controller.yml"

- name: Create migration plan
  k8s:
    state: present
    definition: "{{ lookup('template', 'mig-plan.yml.j2') }}"

- debug:
    msg: "Created migration plan : {{ migration_plan_name }}"

- name: Process PVs
  import_tasks: process_pvs.yml
  when: pv|default(false)|bool == true

- name: Execute migration
  k8s:
    state: present
    definition: "{{ lookup('template', 'mig-migration.yml.j2') }}"

- debug:
    msg: "Created migration name : {{ migration_name }}"
