---
- name: Allow mig-controller to discover PVs prior migration
  pause:
    seconds: 60

- name: Check migration plan
  k8s_facts:
    kind: MigPlan
    api_version: v1alpha1
    namespace: mig
    name: "{{ migration_plan_name }}" 
  register: mig_plan

- name: Check for discovered PVs
  set_fact:
    pvs_discovered: "{{ item }}"
  loop: "{{ mig_plan.resources[0].spec.persistentVolumes }}"
  register: all_pvs

- name: Build list of discovered PVs 
  set_fact: 
    pv_list: "{{ all_pvs.results | map(attribute='ansible_facts.pvs_discovered.name') | list }}" 

- debug:
    msg:
    - "PVs discovered: {{ pv_list | join(' ') }}"
    - "PV action: {{ pv_action }}"

- name: Update migration plan with PVs..
  k8s:
    state: present
    definition: "{{ lookup('template', 'mig-plan-pv.yml.j2') }}"
