- name: Get pod info
  k8s_facts:
    kind: Pod
    namespace: mysql-persistent
    label_selectors: "deployment=mysql-1"
  register: pod

- name: Get size before
  shell: cat {{ playbook_dir }}/roles/pvc/mysql_pvc_database/files/database_info.txt | head -n 1
  register: size_before

- name: Get checksum before
  shell: cat {{ playbook_dir }}/roles/pvc/mysql_pvc_database/files/database_info.txt | tail -1
  register: checksum_before

- name: Check if data are restored
  vars:
    pod_name: "{{ pod.resources[0].get('metadata', {}).get('name', '') }}"
  shell: oc exec -n mysql-persistent {{ pod_name }} -- /bin/bash -c "du -h /var/lib/mysql | awk '/MYSQL_DATABASE/ {print}' | cut -f1"
  register: database_size
  until: database_size.get("stdout", "") == "{{ size_before.get("stdout", "") }}"

- name: Check the checksum of the database file
  vars:
    pod_name: "{{ pod.resources[0].get('metadata', {}).get('name', '') }}"
  shell: oc exec -n mysql-persistent {{ pod_name }} -- /bin/bash -c "md5sum /var/lib/mysql/data/MYSQL_DATABASE/t1.ibd | cut -d ' ' -f 1"
  register: database_checksum
  until: database_checksum.get("stdout", "") == "{{ checksum_before.get("stdout", "") }}"
