- name: Check that mig-controller repo exists
  stat:
    path: "{{ playbook_dir }}/mig-controller"
  register: repo

- name: Clone the mig-controller repo
  git:
    repo: 'https://github.com/fusor/mig-controller.git'
    dest: "{{ playbook_dir }}/mig-controller"
    force: true
  when: not repo.stat.exists
