- name: Delete resources
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
  loop: "{{ namespaces_to_delete }}"

- name: Wait 2 minutes for namespace to be deleted
  k8s_facts:
    kind: Namespace
    api_version: v1
    name: "{{ item }}"
  register: ns
  until: not ns.get("resources", [""])
  retries: 80
  delay: 3
  loop: "{{ namespaces_to_delete }}"
