- name: Create resources
  block:
    - name: Deploy mysql with pvc from yml
      k8s:
        state : present
        definition: "{{ lookup('file', 'mysql-persistent-template.yml')}}"

    - name: Check if deployed and bound
      include: check.yml

    - name: Populate the database with test data
      when: with_data
      vars:
        pod_name: "{{ pod.resources[0].get('metadata', {}).get('name', '') }}"
        src: "{{ playbook_dir }}/roles/pvc/mysql_pvc/files/"
        dest: /opt/app-root/src
      shell: |
              oc rsync -n mysql-persistent {{ src }} {{ pod_name }}:{{ dest }} --exclude=* --include=*.sql
              oc exec -n mysql-persistent {{ pod_name }} -- /bin/bash -c "mysql -uMYSQL_USER -pMYSQL_PASSWORD MYSQL_DATABASE < data.sql"

  when: with_resources

- name: Saving the information about the database for tests
  vars:
    pod_name: "{{ pod.resources[0].get('metadata', {}).get('name', '') }}"
  block:
  - name: Get the size of the database
    shell: oc exec -n mysql-persistent {{ pod_name }} -- /bin/bash -c "du -h /var/lib/mysql | awk '/MYSQL_DATABASE/ {print}' | cut -f1"
    register: database_size

  - name: Get the checksum of the database
    shell: oc exec -n mysql-persistent {{ pod_name }} -- /bin/bash -c "md5sum /var/lib/mysql/data/MYSQL_DATABASE/t1.ibd | cut -d ' ' -f 1"
    register: database_checksum

  - name: Copy files into testing directory
    lineinfile:
      path: "{{ playbook_dir }}/roles/pvc/mysql_pvc_database/files/database_info.txt"
      line: "{{ item }}"
      insertafter: EOF
      create: yes
    with_items:
      - "{{ database_size.stdout }}"
      - "{{ database_checksum.stdout }}"

- name: Create a backup
  when: with_backup
  block:
    - name: Create backup
      include_role:
        name: backup

- name: Restore service
  when: with_restore
  block:
    - name: Start restoring
      include_role:
        name: restore

    - name: Check if restored and bound
      include: check.yml
