---
- name: "Check if {{ item | default('BackupStarted') }} phase is active"
  k8s_facts:
    kind: MigMigration
    api_version: v1alpha1
    namespace: mig
    name: "{{ migration_name }}" 
  register: mig_phase
  until: mig_phase.resources[0].get("status", {}).get("phase", "") ==  item
  retries: 60
  delay: 5
  with_items:
    - "BackupStarted"
    - "RestoreStarted"
    - "Completed"
